import { BarChart3, CheckCircle2, Circle, ShieldCheck, Sparkles } from 'lucide-react';
import type { AttemptStepId, Submission } from './attempt.types';

const rubric = [['Requirement understanding', '15%'], ['Responsibilities', '20%'], ['Encapsulation and interfaces', '10%'], ['Relationships and coupling', '10%'], ['Extensibility', '15%'], ['Behavior and core flow', '10%'], ['Edge cases and robustness', '10%'], ['Reasoning and trade-offs', '10%']];

export default function AttemptOverview({ submission, step }: { submission: Submission; step: AttemptStepId }) {
  const completed = Object.values(submission).filter((value) => value.trim().length >= 12).length;
  const percent = Math.round((completed / 6) * 100);
  return <section className="mb-6 grid gap-4 xl:grid-cols-[1.1fr_1.9fr]"><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-start justify-between gap-4"><div><p className="flex items-center gap-2 text-xs font-bold uppercase tracking-wider text-indigo-600"><Sparkles className="h-3.5 w-3.5" /> Attempt workspace</p><h2 className="mt-2 text-lg font-bold text-slate-900">Build evidence, not just answers.</h2><p className="mt-1 text-sm leading-relaxed text-slate-500">Your design will be checked against the visible rubric below.</p></div><span className="grid h-12 w-12 place-items-center rounded-full border-[5px] border-indigo-100 border-t-indigo-600 text-xs font-bold text-indigo-700">{percent}%</span></div><div className="mt-5 h-2 overflow-hidden rounded-full bg-slate-100"><div className="h-full rounded-full bg-gradient-to-r from-indigo-600 to-violet-500 transition-all" style={{ width: `${percent}%` }} /></div><div className="mt-2 flex justify-between text-xs text-slate-400"><span>{completed} of 6 sections ready</span><span>Current: {step === 'review' ? 'Review' : step}</span></div></div><div className="rounded-2xl border border-slate-200 bg-white p-5 shadow-sm"><div className="flex items-center gap-2"><ShieldCheck className="h-4 w-4 text-emerald-500" /><h2 className="text-sm font-bold text-slate-800">Evaluation rubric</h2><span className="ml-auto text-[10px] font-medium text-slate-400">100% total</span></div><div className="mt-4 grid gap-x-5 gap-y-3 sm:grid-cols-2">{rubric.map(([label, weight]) => <div key={label} className="flex items-center gap-2 text-xs"><BarChart3 className="h-3.5 w-3.5 shrink-0 text-indigo-400" /><span className="min-w-0 flex-1 truncate text-slate-600">{label}</span><b className="text-slate-400">{weight}</b></div>)}</div></div></section>;
}

export function ReadinessChecklist({ submission }: { submission: Submission }) {
  const items = [['Requirements and assumptions', submission.requirements && submission.assumptions], ['Classes and responsibilities', submission.entities], ['Relationships and core flow', submission.relationships && submission.flow], ['Trade-offs and edge cases', submission.tradeoffs]];
  return <div className="rounded-2xl border border-slate-200 bg-slate-50 p-5"><h3 className="text-xs font-bold uppercase tracking-wider text-slate-500">Submission readiness</h3><div className="mt-4 grid gap-3 sm:grid-cols-2">{items.map(([label, value]) => <div key={label} className="flex items-center gap-2 text-sm text-slate-600">{value ? <CheckCircle2 className="h-4 w-4 text-emerald-500" /> : <Circle className="h-4 w-4 text-slate-300" />}{label}</div>)}</div></div>;
}
