import { FileText, Lightbulb } from 'lucide-react';
import { ATTEMPT_STEPS, type AttemptStepId } from './attempt.types';

const tips: Record<AttemptStepId, string[]> = {
  requirements: ['Separate must-have behavior from out-of-scope ideas.', 'Make assumptions explicit so the evaluator can assess your reasoning.'],
  entities: ['Use nouns for models and keep state ownership clear.', 'Avoid adding an abstraction without a real variation point.'],
  relationships: ['Describe who owns behavior, not only how objects connect.', 'Prefer cohesive objects with narrow collaboration boundaries.'],
  flow: ['Write the happy path first, then show where state changes.', 'Name the object responsible for each important decision.'],
  tradeoffs: ['Discuss concurrency, failures, and requirement changes.', 'Explain the cost of your choice and the alternative you rejected.'],
  review: ['Check every requirement against concrete evidence.', 'A different design can be valid when its trade-offs are justified.'],
};

export default function AttemptHelperPanel({ step, tab, onTabChange }: { step: AttemptStepId; tab: 'tips' | 'reference'; onTabChange: (tab: 'tips' | 'reference') => void }) {
  const currentStep = ATTEMPT_STEPS.find((item) => item.id === step);
  return <aside className="space-y-5 xl:sticky xl:top-6 xl:w-[340px] xl:shrink-0 xl:self-start"><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex border-b border-slate-100 bg-slate-50 p-1"><button type="button" onClick={() => onTabChange('tips')} className={`flex flex-1 items-center justify-center gap-2 rounded-xl py-3 text-xs font-bold ${tab === 'tips' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}><Lightbulb className="h-3.5 w-3.5" />Hints</button><button type="button" onClick={() => onTabChange('reference')} className={`flex flex-1 items-center justify-center gap-2 rounded-xl py-3 text-xs font-bold ${tab === 'reference' ? 'bg-white text-indigo-700 shadow-sm' : 'text-slate-500'}`}><FileText className="h-3.5 w-3.5" />Reference</button></div><div className="p-5">{tab === 'tips' ? <><p className="text-[10px] font-bold uppercase tracking-wider text-slate-400">Focus for {currentStep?.label}</p><ul className="mt-4 space-y-4">{tips[step].map((tip, index) => <li key={tip} className="flex gap-3 text-sm leading-relaxed text-slate-600"><span className="grid h-5 w-5 shrink-0 place-items-center rounded bg-indigo-50 text-[10px] font-bold text-indigo-600">{index + 1}</span>{tip}</li>)}</ul></> : <><p className="text-xs font-bold uppercase tracking-wider text-slate-400">Problem summary</p><p className="mt-3 rounded-xl bg-slate-50 p-4 text-sm leading-relaxed text-slate-600">Parking Lot requires multi-level allocation, vehicle-specific spots, tickets, payments, capacity limits, and extensible pricing.</p><div className="mt-4 flex flex-wrap gap-2">{['Multi-level', 'Vehicle types', 'Ticketing', 'Pricing', 'Capacity'].map((tag) => <span key={tag} className="rounded-md bg-slate-100 px-2 py-1 text-[10px] font-medium text-slate-500">{tag}</span>)}</div></>}</div></section><div className="rounded-2xl border border-indigo-100 bg-gradient-to-br from-indigo-50 to-violet-50 p-5"><p className="text-sm font-semibold leading-relaxed text-indigo-900">A good architecture allows major decisions to be deferred.</p><p className="mt-2 text-[10px] font-bold uppercase tracking-wider text-indigo-500">Robert C. Martin</p></div></aside>;
}
