import { ArrowRight, BarChart3, Check, ChevronDown, Clock3, Star, Trophy } from 'lucide-react';
import { Link } from 'react-router-dom';

const metrics = [['Problems Solved', '12', '+3 this week', Trophy, 'text-emerald-500'], ['Total Attempts', '28', '+6 this week', BarChart3, 'text-indigo-500'], ['Average Score', '78%', '+5%', Star, 'text-indigo-500'], ['Practice Time', '12.5 hrs', '+2.3 hrs', Clock3, 'text-indigo-500']] as const;
const problems = [['Elevator', 'Intermediate', 'Design an elevator system with multiple elevators, scheduling and floor requests.', '30–45 min'], ['Vending Machine', 'Beginner', 'Design a vending machine with product inventory, payment handling and dispensing logic.', '20–30 min'], ['Library Management', 'Advanced', 'Design a library system with books, members, borrowing and reservations.', '40–60 min']];

export function DashboardIntro({ name }: { name: string }) { return <section className="relative mb-3 overflow-hidden rounded-lg bg-[linear-gradient(100deg,#fff_58%,#eef2ff)] px-2 py-2.5"><p className="text-[9px] text-slate-500">Good to see you again 👋</p><h1 className="mt-0.5 text-[20px] font-bold leading-none tracking-tight text-slate-900">Keep Practicing, <span className="text-indigo-600">{name.split(' ')[0]}!</span></h1><p className="mt-1 text-[9px] font-medium text-slate-600">Solve. Learn. Get Feedback. Become a better designer.</p><div className="absolute right-3 top-3 hidden max-w-[180px] rounded-lg bg-white/80 px-4 py-2 shadow-sm lg:block"><p className="text-[8px] italic leading-relaxed text-slate-600"><b className="mr-2 text-xl text-indigo-500">“</b>The expert in anything<br />was once a beginner.”</p><p className="mt-1 text-right text-[7px] text-slate-400">— Helen Hayes</p></div></section>; }

export function Metrics() { return <section className="grid grid-cols-2 gap-2 lg:grid-cols-4">{metrics.map(([label, value, change, Icon, tone]) => <article key={label} className="rounded-lg border border-slate-100 bg-white p-2.5 shadow-[0_2px_8px_rgba(15,23,42,.03)]"><div className="flex items-center gap-2"><span className="grid h-6 w-6 place-items-center rounded-md bg-indigo-50"><Icon className={`h-3.5 w-3.5 ${tone}`} /></span><div><p className="text-[7px] text-slate-500">{label}</p><p className="text-sm font-bold leading-tight text-slate-900">{value}</p></div></div><p className="mt-1 pl-8 text-[7px] text-emerald-500">↑ {change}</p></article>)}</section>; }

function Panel({ title, action, children, className = '' }: { title: string; action?: string; children: React.ReactNode; className?: string }) { return <section className={`rounded-lg border border-slate-100 bg-white p-3 shadow-[0_2px_8px_rgba(15,23,42,.03)] ${className}`}><div className="mb-2 flex items-center justify-between"><h2 className="text-[10px] font-bold text-slate-800">{title}</h2>{action && <button className="text-[7px] font-medium text-indigo-600">{action} →</button>}</div>{children}</section>; }

export function ContinuePractice() { return <Panel title="Continue Practicing" action="View All Problems"><div className="flex items-center gap-3 rounded-md border border-slate-100 p-2.5"><span className="grid h-9 w-9 place-items-center rounded-lg bg-indigo-50 text-lg">🚙</span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h3 className="text-[10px] font-bold text-slate-800">Parking Lot</h3><span className="rounded bg-emerald-50 px-1.5 py-0.5 text-[7px] text-emerald-600">Beginner</span></div><p className="mt-1 text-[7px] leading-relaxed text-slate-500">Design a parking lot with multiple floors, different vehicle types, and efficient parking strategies.</p><div className="mt-1 flex gap-1"><Tag text="OOP" /><Tag text="Design Patterns" /><Tag text="Scalability" /></div></div><div className="hidden w-36 sm:block"><div className="flex justify-between text-[7px] text-slate-500"><span>Your Progress</span><span>1/3 attempts</span></div><div className="mt-1 h-1 rounded bg-slate-200"><i className="block h-full w-1/3 rounded bg-indigo-500" /></div><Link to="/problems/parking-lot" className="mt-2 flex h-5 items-center justify-center rounded bg-indigo-600 text-[7px] font-medium text-white">Continue Practice <ArrowRight className="ml-1 h-2.5 w-2.5" /></Link></div></div></Panel>; }

export function Streak() { return <Panel title="🔥 Streak" className="relative overflow-hidden"><div className="absolute right-4 top-4 text-xs text-indigo-500">Keep it going!</div><p className="text-lg font-bold text-slate-900">7 days</p><div className="mt-4 flex justify-between">{['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map((day, i) => <span key={day} className="text-center text-xs text-slate-400"><i className={`mb-1 grid h-7 w-7 place-items-center rounded-full ${i === 6 ? 'bg-slate-100' : 'bg-indigo-600 text-white'}`}>{i < 6 && <Check className="h-4 w-4" />}</i>{day}</span>)}</div><p className="mt-4 text-center text-xs text-slate-500">“A little progress each day adds up<br />to big results.”</p></Panel>; }

export function OtherProblems() { return <Panel title="Other Problems for You" action="View All Problems"><div className="grid gap-2 md:grid-cols-3">{problems.map(([name, level, description, duration]) => <article key={name} className="rounded border border-slate-100 p-2"><div className="flex items-start gap-2"><span className="grid h-6 w-6 place-items-center rounded bg-indigo-50 text-sm">{name === 'Elevator' ? '↕' : name === 'Vending Machine' ? '▣' : '▥'}</span><div className="min-w-0 flex-1"><div className="flex justify-between gap-1"><h3 className="text-[8px] font-semibold text-slate-700">{name}</h3><span className="text-[6px] text-indigo-500">{level}</span></div><p className="mt-1 h-7 overflow-hidden text-[6px] leading-relaxed text-slate-400">{description}</p></div></div><div className="mt-1.5 flex items-center justify-between text-[7px] text-slate-400"><span>◷　{duration}</span><button className="grid h-4 w-4 place-items-center rounded-full bg-indigo-50 text-indigo-500"><ArrowRight className="h-2 w-2" /></button></div></article>)}</div></Panel>; }

export function Goals() { return <Panel title="Your Goals" action="Edit Goals"><div className="space-y-2.5">{[['Solve 5 problems this week','3/5'],['Maintain 70%+ average score','78%'],['Practice for 10 hours','6.5/10 hrs']].map(([label, value], index) => <div key={label}><div className="flex justify-between text-[7px] text-slate-500"><span>{index === 0 ? '🎯 ' : index === 1 ? '🛠 ' : '🕘 '}{label}</span><span>{value}</span></div><div className="mt-1 h-1 rounded-full bg-slate-100"><i className="block h-full rounded-full bg-indigo-500" style={{ width: index === 0 ? '60%' : index === 1 ? '78%' : '65%' }} /></div></div>)}</div></Panel>; }

export function RecentAttempts() { return <Panel title="Recent Attempts" action="View All"><table className="w-full text-left text-[7px]"><thead className="border-b border-slate-100 text-slate-400"><tr><th className="pb-1 font-medium">Problem</th><th className="pb-1 font-medium">Attempted On</th><th className="pb-1 font-medium">Score</th><th className="pb-1 font-medium">Status</th><th className="pb-1 font-medium">Action</th></tr></thead><tbody>{[['▣　Vending Machine','Sep 8, 2026','82%','Completed','View →'],['🚙　Parking Lot','Sep 6, 2026','68%','Completed','View →'],['↕　Elevator','Sep 4, 2026','—','In Progress','Continue →']].map(([problem,date,score,status,action]) => <tr key={problem} className="border-b border-slate-50 last:border-0 text-slate-600"><td className="py-1.5">{problem}</td><td>{date}</td><td>{score}</td><td><span className={`rounded px-1.5 py-0.5 ${status === 'Completed' ? 'bg-emerald-50 text-emerald-600' : 'bg-indigo-50 text-indigo-600'}`}>{status}</span></td><td className="text-indigo-500">{action}</td></tr>)}</tbody></table></Panel>; }

export function Insights() { return <Panel title="Learning Insights"><button className="absolute right-4 -mt-5 flex items-center gap-1 rounded border border-slate-100 px-1.5 py-1 text-[7px] text-slate-500">This Week <ChevronDown className="h-2 w-2" /></button><div className="flex items-center justify-center gap-5"><div className="grid h-20 w-20 place-items-center rounded-full border-[18px] border-indigo-100"><span className="text-[8px] font-semibold text-indigo-600">78%</span></div><div className="space-y-2 text-[7px] text-slate-500"><p><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-indigo-600" />Your Score</p><p><i className="mr-1 inline-block h-1.5 w-1.5 rounded-full bg-indigo-100" />Peer Average</p></div></div></Panel>; }
function Tag({ text }: { text: string }) { return <span className="rounded bg-slate-100 px-1 py-0.5 text-[6px] text-slate-500">{text}</span>; }
